services:
  alloydb-omni-postgis:
    build: ./build
    restart: always
    container_name: alloydb-omni-postgis
    shm_size: 4g
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PG_DATA: /var/lib/alloydb/data
    ports:
      - 5432:5432
    volumes:
      - alloydbdata:/var/lib/alloydb/data

volumes:
  alloydbdata:
